# Change these first
owner: avranju # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nerdworks Blog
    url: https://blogorama.nerdworks.in
  - name: Back To The Garden
    url: https://backtothegarden.in
  - name: Nerdworks AI
    url: https://ai.nerdworks.dev
  - name: Nerdworks LiteLLM
    url: https://litellm.nerdworks.dev
  - name: Nerdworks N8N
    url: https://n8n.nerdworks.dev
  - name: Nerdworks Convex API Prod
    url: https://convex.api.nerdworks.dev
  - name: Nerdworks Convex Dashboard Prod
    url: https://convex.dashboard.nerdworks.dev
  - name: Nerdworks Convex API Dev
    url: https://dev.convex.api.nerdworks.dev
  - name: Nerdworks Convex Dashboard Dev
    url: https://dev.convex.dashboard.nerdworks.dev
  - name: Court Capo
    url: https://courtcapo.nerdworks.dev
  - name: Nerdworks Search
    url: https://search.nerdworks.dev
  - name: Nerdworks Writebook
    url: https://writebook.nerdworks.dev
  - name: Musings Blog
    url: https://musings.nerdworks.dev/
  - name: Remark42 Comments on Musings Blog
    url: https://remark42.nerdworks.dev/api/v1/config?site=remark
  - name: ToteUp AD Auth
    url: https://toteupad.nerdworks.dev/device.html
  # - name: Elections Lab
  #  url: https://elections.nerdworks.dev/lab
  # - name: ToteUp API
  #  url: https://toteup.nerdworks.dev
  # - name: Yodlee Proxy
  #  url: https://yodlee-proxy.nerdworks.dev

assignees:
  - avranju

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: gh.nerdworks.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nerdworks Upptime
  introTitle: "Nerdworks **Upptime**: Up-time monitor for all my sites & services"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/avranju/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
